FROM node:20 AS build
WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npx tsc

FROM node:20-alpine
WORKDIR /app

COPY --from=build /app/dist ./dist

COPY package*.json ./
RUN npm install --production

EXPOSE 3001
CMD ["node", "dist/server.js"]
